version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: "host"
    ports:
      - 15672:15672
      - 5672:5672

  config-server:
    build: config-server/
    container_name: config-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8888:8888

  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8076:8076
  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8086:8086
  mysql:
    container_name: "mysql-user"
    image: mysql
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=jwt_auth_IG
      - MYSQL_PASSWORD=root123
  mongodb-service:
    image: mongo:latest
    container_name: "mongodb-service"
    restart: always
    hostname: localhost
    ports:
      - 27017:27017

  user-service:
    build: user-service/
    container_name: user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8085:8085

  email-service:
    build: email-service/
    container_name: email-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8084:8084

  authentication-service:
    build: authentication-service/
    container_name: authentication-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8081:8081

  customer-service:
    build: customer-service/
    container_name: customer-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8082:8082

  designer-service:
    build: designer-service/
    container_name: designer-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8083:8083

  payment-service:
    build: payment-service/
    container_name: payment-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9097:9097

  order-service:
    build: order-service/
    container_name: order-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8087:8087

  feedback-service:
    build: feedback-service/
    container_name: feedback-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8086:8086