eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show:
        details: always


    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled: true

spring:
  application:
    name: api-gateway
    main:
      web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8085/
          predicates:
            - Path=/userService/**
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/authenticationService/**
        - id: customer-service
          uri: http://localhost:8082/
          predicates:
            - Path=/customerService/**
        - id: designer-service
          uri: http://localhost:8083/
          predicates:
            - Path=/designerService/**
        - id: email-service
          uri: http://localhost:8084/
          predicates:
            - Path=/emailService/**
        - id: order-service
          uri: http://localhost:8087/
          predicates:
            - Path=/orderService/**
        - id: payment-service
          uri: http://localhost:9097/
          predicates:
            - Path=/paymentService/**
        - id: feedback-service
          uri: http://localhost:8086/
          predicates:
            - Path=/feedbackService/**
















