eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8777

spring:
  application:
    name: API_GATEWAY

cloud:
  gateway:
    routes:
      - id: USER_SERVICE
        uri: lb://USER_SERVICE
        predicates:
          - Path=/user/**
          - - id: AUTHENTICATION_SERVICE
              uri: lb://AUTHENTICATION_SERVICE
              predicates:
                - Path=/user/**
                - id: CUSTOMER_SERVICE
                  uri: lb://CUSTOMER_SERVICE
                  predicates:
                    - Path=/user/**
                    - id: DESIGNER_SERVICE
                      uri: lb://DESIGNER_SERVICE
                      predicates:
                        - Path=/api/v2/**
                        - id: PAYMENT_SERVICE
                          uri: lb://PAYMENT_SERVICE
                          predicates:
                            - Path=/payment/**
