client: 'null'
defaultZone: http://localhost:8761/eureka
eureka: 'null'
fetch-registry: true
instance:
    hostname: localhost
register-with-eureka: true
server:
    port: 8585
service-url: 'null'
spring:
    application:
        name: user-service
    data:
        mongodb:
            database: user_registration
    main:
        allow-circular-references: true
