server:
    port: 8585
spring:
    data:
        mongodb:
            database: user_registration
    main:
        allow-circular-references: true

    application:
        name: user-service
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: root
#        password: root123