client: ''
defaultZone: http://localhost:8761/eureka
eureka: ''
fetch-registry: true
hostname: localhost
instance: ''
register-with-eureka: true
server:
    port: 8089
service-url: ''
spring:
    application:
        name: EMAIL_SERVICE
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        password: ytttxtfkdejifbid
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
                        required: 'true  '
        smtp:
            ssl:
                trust: 'smtp.gmail.com  '
        test-connection: false
        username: interiors.gateway@gmail.com
